#!/usr/bin/env bash
#
# bootstrap the basics

# check for homebrew
# install git
# install xcode
# git dotfile repository
# install oh-my-zsh
# install zsh
# add to .profile

# install homebrew
echo -n "checking for homebrew"
if ! command -v brew > /dev/null; then
    echo " - installing"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    export PATH="/usr/local/bin:$PATH"
else
    echo " - installed"
fi


#install git
echo "installing git"
brew install git

if ! [ -f ../git/gitconfig.local.symlink ]
then
    echo 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    echo -n ' - What is your github author name?'
    read -e git_authorname
    echo -n ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" ../git/gitconfig.local.symlink.example > ../git/gitconfig.local.symlink

fi

#install zsh
echo "installing oh-my-zsh"
unset ZSH
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

#install zsh
brew install zsh

#setup .profile to point to zsh
rm -f ~/.profile
echo "export SHELL=/usr/local/bin/zsh" > ~/.profile
echo "[ -z "$ZSH_VERSION" ] && exec /usr/local/bin/zsh -l" >> ~/.profile



