#! /usr/bin/env bash

# DESCRIPTION
# Installs Homebrew software.

brew analytics off
## make sure everything already install is epgraded
brew update
brew upgrade
brew cleanup

brew tap homebrew/bundle

brew cask install java
brew install ack
brew install coreutils
brew install wget
brew install youtube-dl
brew install readline
brew install openssl

# OpenSSL OSX CA
brew tap raggi/ale
brew install openssl-osx-ca

brew install asciinema
brew install bash
brew install bash-completion
brew install chruby
brew install ctags
brew install diff-so-fancy
brew install direnv
brew install exiftool
brew install fasd
brew install fortune
brew install ffmpeg
brew install gdbm
brew install gifsicle
brew install git
brew install gpg
brew install gpg-agent
brew install hr
brew install imagemagick
brew install libffi
brew install libyaml
brew install lnav
brew install lynis
brew install mas
brew install ngrep
brew install node
brew install phantomjs
brew install pv
brew install python3
pip2 install virtualenv
pip3 install virtualenv


#brew install xquartz
brew install texinfo
brew tap homebrew/science
brew install Caskroom/cask/xquartz
brew install r
brew install dcmtk
brew install gocr

brew install ruby-install
brew install terminal-notifier
brew install tree
brew install vim
brew install watchman
brew install yank
brew install zsh-syntax-highlighting
brew install zsh-history-substring-search
brew install zsh-autosuggestions
brew install zsh-completions
brew install zsh-lovers
brew install zshdb
