#! /usr/bin/env bash

# DESCRIPTION
# Installs App Store software.

# EXECUTION
# check for mas
if ! command -v mas > /dev/null; then
  printf "ERROR: Mac App Store CLI (mas) can't be found.\n"
  printf "       Please ensure Homebrew and mas (i.e. brew install mas) have been installed first."
  exit 1
fi


# Airmail
mas install 918858936
# Deliveries
mas install 924726344
# Keynote
mas install 409183694

# Home Inventory
mas install 413564952



# PDFOutliner
mas install 420874236

# Kindle
mas install 405399194

# Monosnap
mas install 540348655


# Jump Desktop
mas install 524141863

# Numbers
mas install 409203825

# Pedbone
mas install 844554641

# Pages
mas install 409201541

# WiFi Explorer
mas install 494803304

# Bible Study
mas install 472790630


printf "manually install:\n"
printf " Cisco Anyconnect\n"
printf " Comic Life 3\n"
printf " Scrivener\n"
printf " AirDisplay\n"
printf " iFlash\n"
