#!/usr/bin/env bash

rootdir=$HOME/src/perl5/
if ! [ -d "$HOME/src" ] ; then
  mkdir $HOME/src ;
fi
if ! [ -d "$rootdir" ] ; then
  curl -L https://install.perlbrew.pl | bash
  source $HOME/src/perl5/etc/bashrc
  perlbrew init
  perlbrew install-patchperl
  perlbrew install-cpanm
  perlbrew install stable
  perlbrew list
  perlbrew switch perl-5.24.1
fi
