#! /usr/bin/env bash

# DESCRIPTION
# Installs R modules

install_RMod () {
  mirror="http://cran.us.r-project.org"
  echo -n "installing $1"
  R --vanilla --quiet -e "install.packages('$1', repos='http://cran.us.r-project.org')"
}

install_RMod rmarkdown
install_RMod plotly
install_RMod lattice
install_RMod ggplot2
install_RMod ggmap
install_RMod oro.dicom
install_RMod imager

