#!/usr/bin/env bash

rootdir=$HOME/src/perl5/perlbrew
if ! [ -d "$HOME/src" ] ; then
  mkdir $HOME/src ;
fi
if ! [ -d "$rootdir" ] ; then
  curl -L https://install.perlbrew.pl | bash
  source $HOME/src/perl5/perlbrew/etc/bashrc
  perlbrew init
  perlbrew install-patchperl
  perlbrew install-cpanm
  perlbrew install stable
fi

cpanm App::cpanoutdated
cpanm YAML
cpanm local::lib
cpanm LWP::UserAgent
cpanm LWP::Simple
cpanm HTTP::Request::Common
#cpanm HTTP::FormatText
cpanm WWW::Mechanize
cpanm WWW::Twilio::API
cpanm Email::Send
cpanm Email::Send::Gmail
#cpanm Email::Send::Creator
cpanm Switch
cpanm DateTime::Format::Strptime
cpanm WebService::Google::Voice::SendSMS
cpanm IPC::Open2
cpanm XML::Twig
cpanm URI::Escape
cpanm Data::Dumper
cpanm Time::HiRes
cpanm Digest::MD5
cpanm Digest::MD5::File




