#!/usr/bin/env bash
cpanm Log::Log4perl
cpanm Test::Memory::Cycle
cpanm Test::Exception
cpanm local::lib
cpanm App::cpanoutdated
cpanm YAML
cpanm LWP::UserAgent
cpanm LWP::Simple
cpanm HTTP::Request::Common
#cpanm HTTP::FormatText
cpanm WWW::Mechanize
cpanm WWW::Twilio::API
cpanm Email::Send
cpanm Email::Send::Gmail
#cpanm Email::Send::Creator
cpanm Switch
cpanm DateTime::Format::Strptime
cpanm WebService::Google::Voice::SendSMS
cpanm IPC::Open2
cpanm XML::Twig
cpanm URI::Escape
cpanm Data::Dumper
cpanm Time::HiRes
cpanm Digest::MD5
cpanm Digest::MD5::File




