#! /usr/bin/env bash

# DESCRIPTION
# Installs Homebrew Casks.
installCask () {
  fileName="/Applications/$1.app"
  echo -n "checking $fileName"
  if [ ! -d "$fileName" ] ; then
    brew cask install $2 ;
  else
    echo " - installed"
  fi
}
installCask 'Alfred 3' alfred
installCask 'AppCleaner' appcleaner
installCask 'Bartender 2' bartender
installCask 'Dropbox' dropbox
installCask 'Firefox' firefox
installCask 'Google Chrome' google-chrome
installCask 'HandBrake' handbrake
installCask 'iStat Menus' istat-menus
installCask 'iTerm' iterm2
installCask 'Opera' opera
installCask 'Visual Studio Code' visual-studio-code
installCask 'VLC' vlc
