#! /usr/bin/env bash

# DESCRIPTION
# Installs applications.

# EXECUTION

# CheatSheet
#install_zip_app "$CHEATSHEET_APP_URL" "$CHEATSHEET_APP_NAME"

# OmniGraffle
#install_dmg_app "$OMNIGRAFFLE_APP_URL" "$OMNIGRAFFLE_VOLUME_NAME" "$OMNIGRAFFLE_APP_NAME"

# Sublime Text URL Handler
#install_zip_app "$SUBLIME_URL_HANDLER_APP_URL" "$SUBLIME_URL_HANDLER_APP_NAME"

# install oh-my-zsh
#unset ZSH
#sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
##git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
