#!/usr/bin/env bash

#visual studio installs
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension PeterJausovec.vscode-docker
code --install-extension casian.plsql
code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.python
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension lukehoban.Go
code --install-extension mitaki28.vscode-clang
code --install-extension ms-vscode.cpptools
code --install-extension robertohuertasm.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension yzane.markdown-pdf
code --install-extension zxh404.vscode-proto3

